spring:
  application:
    name: patient-service

# Uncomment the following lines to enable H2 database for development
#  h2:
#    console:
#      path: /h2-console
#  datasource:
#    url: jdbc:h2:mem:patient_db
#    driver-class-name: org.h2.Driver
#    username: admin
#    password: admin
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#    hibernate:
#      ddl-auto: update
#  sql:
#    init:
#      mode: always

server:
  port: 4000
logging:
  level:
    root: info

open:
  api:
    info:
      title: Patient Service API
      version: 1.0.0
      description: API for managing patient
      server:
        url: http://localhost:4000
        description: Local server
      group:
        name: patient
        package-to-scan: com.tiencv.patientservice

